export { helpCommand } from './help';
export { clearCommand } from './clear';
export { pwdCommand, cdCommand, lsCommand } from './navigation';
export { catCommand, touchCommand, mkdirCommand, rmCommand } from './files';
export { exportCommand, importCommand } from './data';
export { personaCommand } from './persona';
export { contactCommand } from './contact';
export { groupCommand } from './group';
export { fileCommand } from './file';
export { configCommand } from './config';
export { typeindexCommand } from './typeindex';
export { exitCommand } from './exit';
export { scriptCommand } from './script';
